### ISSUE TITLE
Cannot get to run certain methods (get_open_orders, limit_buy, etc.)

### ISSUE THREAD

**Issue by Hill333** [erhan/pybtcturk#3]
Nice wrapper, thanks for sharing this with community.

I cannot get to run most of private requests such as get_open_orders. I have read a similar issue posted above and I confirm my private & public keys are correct because I can run client.get_balances() with no issues.

from btcturk import Btcturk
client = Btcturk('XXX-914b78f84fc3', 'XXX')

client.get_balances()
{'btc_available': 0.0,
 'btc_balance': 0.0,
 'btc_reserved': 0.0,
 'btctry_maker_fee_percentage': 0.001694915,
 'btctry_taker_fee_percentage': 0.002542373,
 'eth_available': 0.0,
 'eth_balance': 0.0,
 'eth_reserved': 0.0,
 'ethbtc_maker_fee_percentage': 0.001694915,
 'ethbtc_taker_fee_percentage': 0.002542373,
 'ethtry_maker_fee_percentage': 0.0,
 'ethtry_taker_fee_percentage': 0.001694915,
 'ltc_available': 0.0,
 'ltc_balance': 0.0,
 'ltc_reserved': 0.0,
 'ltctry_maker_fee_percentage': 0.001694915,
 'ltctry_taker_fee_percentage': 0.002542373,
 'try_available': 288.11,
 'try_balance': 789.11,
 'try_reserved': 500.99,
 'usdt_available': 0.0,
 'usdt_balance': 0.0,
 'usdt_reserved': 0.0,
 'usdttry_maker_fee_percentage': 0.001694915,
 'usdttry_taker_fee_percentage': 0.002542373,
 'xlm_available': 0.0,
 'xlm_balance': 0.0,
 'xlm_reserved': 0.0,
 'xlmtry_maker_fee_percentage': 0.001694915,
 'xlmtry_taker_fee_percentage': 0.002542373,
 'xrp_available': 0.0,
 'xrp_balance': 0.0,
 'xrp_reserved': 0.0,
 'xrptry_maker_fee_percentage': 0.001694915,
 'xrptry_taker_fee_percentage': 0.002542373}

client.get_open_orders("ETHTRY")
Traceback (most recent call last):

  File "<ipython-input-8-87e2499f70e3>", line 1, in <module>
    client.get_open_orders("ETHTRY")

  File "C:\Users\fizbe\Anaconda3\envs\arbitrage\lib\site-packages\btcturk\btcturk.py", line 155, in get_open_orders
    return self._make_request(method="GET", path="openOrders", params=params)

  File "C:\Users\fizbe\Anaconda3\envs\arbitrage\lib\site-packages\btcturk\btcturk.py", line 41, in _make_request
    return resp.json()

  File "C:\Users\fizbe\Anaconda3\envs\arbitrage\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)

  File "C:\Users\fizbe\Anaconda3\envs\arbitrage\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)

  File "C:\Users\fizbe\Anaconda3\envs\arbitrage\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\Users\fizbe\Anaconda3\envs\arbitrage\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

**Comment by Hill333** [comment]
I was experiencing issues because my initial API was set only to show balance, I created a new API key with no restrictions and it works fine. No issues with code.
